### ISSUE TITLE
Add taxa w/o brlen

### ISSUE THREAD

**Issue by bomeara** [phylotastic/datelife#13]
bladj, etc. BOLD scaling

**Comment by arlin** [comment]
The issue that concerned me was that we previously had some trees in the portal with fake branch lengths, all set to 1.  I don't know what is the algorithm being used at DateLife, but if you send (A, (B,C)) and (A:1, (B:1,C:1):1) you get different answers (not hugely different, but clearly different in proportion).  I can provide an example.

**Comment by bomeara** [comment]
Done with the GetBoldOToLTree function, but not exposed to users yet. Add option in EstimateDates() function to let users choose this.
