### ISSUE TITLE
indicate in the output which species are not found in opentree chronograms

### ISSUE THREAD

**Issue by LunaSare** [phylotastic/datelife#23]
I think it would be useful for the users to have an element in the EstimateDates output indicating which species where not found in the opentree chronograms with at least two target species.

**Comment by bomeara** [comment]
Sure -- easy to make a field to hold this and display in certain views (like html)

**Comment by LunaSare** [comment]
Thanks, I'm working on it! Although, I was thinking that missing taxa data should be available for all output formats if the user chooses it. Maybe we could add an argument like append.missing.taxa.summary (probably better with a shorter name), which would add the summary of missing taxa as a matrix of presence/absence by source chronogram, or as a vector of percentage of presence among source chronograms. The output would be a list in all formats except for html. What do you think?

**Comment by bomeara** [comment]
maybe `missing.taxa=c('summary', 'list', 'none')` and users could decide what they wanted: a list of all of them, a summary, or nothing.

**Comment by LunaSare** [comment]
Ok. It is now implemented by `SummarizeResults()` function as argument `missing.taxa = c("none", "summary", "matrix")`
By default, it will not add missing.taxa to the output, bit it will print the summary of missing.taxa if `verbose=="taxa"`
