### ISSUE TITLE
add dating with treePL as an alternative to PATHd8

### ISSUE THREAD

**Issue by LunaSare** [phylotastic/datelife#36]
Maybe make a function that can be called when method = "treePL" in various functions, such as CongruifyAndCheck, UseAllCalibrations and GetBoldOToLTree (when implemented)

**Comment by bomeara** [comment]
I've added it in, w a unit test. I've now added it to geiger with a pull request. We'll see if it goes through.

**Comment by bomeara** [comment]
treepl now is in geiger on github. Not on CRAN though.

**Comment by LunaSare** [comment]
Added treePL functions to datelife for now
