### ISSUE TITLE
install packages with datelife

### ISSUE THREAD

**Issue by LunaSare** [phylotastic/datelife#46]
The following packages need to be installed as dependencies:
‘paleotree’ ‘phylocomr’ ‘rphylotastic’ ‘taxize’

**Comment by bomeara** [comment]
Added to suggests. But maybe we want to rewrite test so it doesn't require these?

**Comment by LunaSare** [comment]
they're not used in the tests but in some of the actual datelife functions, so we have to keep them for now. Added to suggests and enhances.
