### ISSUE TITLE
Fix pulling from OToL

### ISSUE THREAD

**Issue by bomeara** [phylotastic/datelife#7]
pulling in chronograms to a cache now fails with errors. Also, the existing cache has some non-chronograms in it. Not sure if this is an `rotl` update issue or something else.

**Comment by josephwb** [comment]
@bomeara if you give me an example call (either one or both to opentree/rotl) I can take a look. :ant:  :bug: :beetle:

**Comment by bomeara** [comment]
ok. I *think* I fixed this, but will check again.

[must use more unit tests, must use more unit tests...]
