### ISSUE TITLE
Issue with DESCRIPTION prevents installation

### ISSUE THREAD

**Issue by vsbuffalo** [phylotastic/datelife#70]
Hi datelife folks,

Thanks for this awesome package! I just wanted to point out that a recent commit is breaking installation and leading to the current build error. I was able to go back and download commit 2ec09a855116fb6e30785549f276c9fa75983986 and manually install with `devtools:::install()` successfully, but wanted to point it out to you all so other folks can install through the usual avenues.

**Comment by LunaSare** [comment]
Thanks @vsbuffalo! Hope it's been working for you ⭐
