### ISSUE TITLE
Documentations tweaks

### ISSUE THREAD

**Issue by snacktavish** [phylotastic/datelife#90]
http://phylotastic.org/datelife/articles/Getting_started_with_datelife.html

The getting started examples run nicely, but a little more info about how to interpret and use the outputs would be helpful.

**Comment by snacktavish** [comment]
https://github.com/phylotastic/datelife/blob/c668b40a91e27b2dc70ed26739946eff329d82f1/README.Rmd#L49

I think adding links to the other "articles" here would help!

**Comment by LunaSare** [comment]
Done here #91
